- name: install mysql 
  ansible.builtin.dnf:
    name: mysql-server
    state: installed
- name: enable and start mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: changes mysql default password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
  register: mysql_output
- name: password_setup
  ansible.builtin.debug:
    msg: "{{ password_setup }}"