- name: app_setup
  include_role: 
    name: common
    tasks_from: app_setup.yaml
- name: nodejs setup
  include_role: 
    name: common
    tasks_from: nodejs

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
- name: check wheather data is load or not
  ansible.builtin.command: mongosh --host mongodb.devops73.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
- name: check data is load or not 
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
- name: load data into mongodb
  ansible.builtin.shell: mongosh --host mongodb.devops73.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml
