- name: create system user roboshop
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app
    system: true

- name: create new directory /app
  ansible.builtin.file:
    path: /app
    state: directory
- name: download {{ component }} project 
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip
    

- name: unzip {{ component }} project
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
