- name: install maven 
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: install maven dependecies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app
- name: rename jar file
  ansible.builtin.command: "mv target/{{ component }}-1.0.jar {{ component }}.jar"
  